### ISSUE TITLE
Don't know if I am getting errors or not

### ISSUE THREAD

**Issue by 123survesh** [crookedneighbor/habitica-node#160]
Hi,
I am trying to setup habitica following : http://habitica.wikia.com/wiki/Setting_up_Habitica_Locally
I am using a Ubuntu 16.04 machine.

While trying to run habitica by performing
npm start

I am faced with some errors but then I got the connected with mongoose status after that. I dont know if I am suffering from some issues or not.

Here is the terminal output I got:
https://paste.ofcode.org/WWN2HjHD2xqm7uvZGLFspX

Please help me out.

**Comment by crookedneighbor** [comment]
This is a module for interacting with the Habitica API in your npm modules. You are looking for: http://github.com/habitrpg/habitica

But for issues around getting set up with Habitica locally, it's usually better to ask your question here: https://habitica.com/groups/guild/68d4a01e-db97-4786-8ee3-05d612c5af6f

**Comment by 123survesh** [comment]
I will do that @crookedneighbor . Thanks for the links :+1:

**Comment by crookedneighbor** [comment]
(though, looking at the stacktrace, it looks like you're using npm 3 when you should be using npm 5)

```
npm install --global npm@5
```

Once you have npm 5 installed, remove your node_modules folder and reinstall

```
rm -rf node_modules
npm install
```

Then `npm start`. If you're still having trouble after that, I recommend asking for help in the guild I posted.

**Comment by 123survesh** [comment]
Oh yes, I am using npm 3. I thought I had the right version installed :sweat_smile: 
Thank you for helping me out @crookedneighbor
